### ISSUE TITLE
Error with Super Metrics Import

### ISSUE THREAD

**Issue by eg01004** [notoriousbdg/vrops-dashboard-roi#1]
Receiving error, "Following Super Metrics contain wrong formulas: Number of fully Deprecated Servers" when attempting import of json file from download.  Please advise.
![Error with JSON import](https://user-images.githubusercontent.com/66781561/84382253-641a5180-abb8-11ea-8c19-3423d4b26736.PNG)

**Comment by notoriousbdg** [comment]
That super metric requires functionality that was added in vROps 8.1.  I recommend upgrading to vROps 8.1 then try importing the super metrics again.

**Comment by cleif** [comment]
@notoriousbdg - is there any supermetric that can be used for similar results? Can I remove that SM from the JSON and import the remaining?
